### ISSUE TITLE
Question! how to download NRT data using tutorial_01 datadownload notebook?

### ISSUE THREAD

**Issue by DavidChoi76** [ghiggi/gpm_api#15]
Hello!! your code is really awesome!!

I'm looking into your code and have a question.
When I changed product, product type, and time, I got an issue "no data found."
Do you know how to solve this issue? 

<img width="925" alt="image" src="https://github.com/ghiggi/gpm_api/assets/23341664/7e2e3445-3744-452f-8cde-5c09ae6e1300">

**Comment by ghiggi** [comment]
Hey @DavidChoi76 

I tested on the latest gpm-api version and the file download works ;) Install the latest version with `pip install gpm-api`
Note that a new IMERG version solving several issues has been recently released, but it requires you to specify the `product='IMERG-FR'` and `product_type="RS"` and `version=7`. 

If the problem persists, reopen the issue ;)
