### ISSUE TITLE
[FEATURE] make GPM V9 available

### ISSUE THREAD

**Issue by kmuehlbauer** [ghiggi/gpm_api#57]
**Is your feature request related to a problem? Please describe.**

`ValueError: GPM-API currently supports only GPM versions 5, 6 and 7.`

**Describe the solution you'd like**
GPM V9 should work successfully.

gpm-api version '0.2.13'

@ghiggi What are the blockers here? I did not yet dive into gpm-api code, but I'm interested enough to contribute. Or is this already in the works?

**Comment by kmuehlbauer** [comment]
Nevermind @ghiggi this seems just some misunderstanding on my side ;-)

**Comment by ghiggi** [comment]
Hey @kmuehlbauer. The version argument refers to the GPM product versions era. The last product version is 7. 
It does not relate to the version of the software ;) 
Let me know if you have any question !

**Comment by kmuehlbauer** [comment]
Yes, I mixed things up. :grimacing:
